###
GET http://localhost:3000/users?offset=0&limit=5&order=oldest 


###
GET http://localhost:3000/users/15f395af-1a64-409b-8042-ebfd2db03245

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "email":"ksot1233@gmail.com",
  "firstName":"go",
  "lastName":"Bong",
  "address": "원주"
}



###
PATCH  http://localhost:3000/users/15f395af-1a64-409b-8042-ebfd2db03245
Content-Type: application/json

{
  "email":"solcom123@naver.com",
  "firstName":"go",
  "lastName":"Bong",
  "address": "경기도"
}



###
DELETE   http://localhost:3000/users/15f395af-1a64-409b-8042-ebfd2db03245




###
GET http://localhost:3000/products?offset=1&order=priceLowest&category=FASHION



###
GET http://localhost:3000/products/f3293c80-a117-419a-a77a-7622058968f4


###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name":"코드잇 후디",
  "description": "코드인 로고가 새겨진 보라색 후디",
  "price": 39000,
  "stock": 10,
  "category": "FASHION"
}


###
PATCH  http://localhost:3000/products/f3293c80-a117-419a-a77a-7622058968f4
Content-Type: application/json

{
  "name":"김한솔 후디",
  "description": "김한솔 로고가 새겨진 파란색 후디",
  "price": 51000,
  "stock": 100,
  "category": "FASHIONN"
}
